/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124665-gaf4caa17a7-20260528"
#endif /* AVUTIL_FFVERSION_H */
